databases:
  - name: urlshorter
    databaseName: urlshorter
    user: urlshorter_user

services:
  - type: web
    name: urlshorter
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urlshorter
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4